FROM maven:3.8.4-jdk-11-slim as builder

WORKDIR /app
COPY /app/worker /app/worker

WORKDIR /app/worker

RUN mvn dependency:resolve

RUN mvn package

FROM openjdk:11-jre-slim

CMD java -jar worker-jar-with-dependencies.jar
