version: '3'
services:

  poll:
    build: ./poll
    ports:
      - 5000:80
    depends_on:
      - redis
    networks:
      - poll-tier

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - poll-tier
      - worker-tier

  worker:
    build: ./worker
    depends_on:
      - redis
      - db
    networks:
      - worker-tier
    ports:
      - 5002:80

  db:
    image: postgres:9.4
    ports:
      - "5432:5432"
    hostname: db
    networks:
      - result-tier
      - worker-tier
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db-data:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  result: 
    build: ./result
    depends_on:
      - db
    networks:
      - result-tier
    ports:
      - 5001:4242


volumes:
  db-data:

networks:
  poll-tier:
  result-tier:
  worker-tier:
