version: '3'
services:

  poll:
    build: ./poll
    restart: always
    ports:
      - 5000:80
    environment:
      REDIS_HOST: redis
    networks:
      - poll-tier

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"
    networks:
      - poll-tier
      - back-tier

  worker:
    build: ./worker
    depends_on:
      - redis
      - db
    restart: always
    networks:
      - back-tier
    environment:
      REDIS_HOST: redis
      
    ports:
      - 5002:80


  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    networks:
      - result-tier
      - back-tier
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres

  
  result: 
    build: ./result
    depends_on:
      - db
    restart: always
    environment:
      REDIS_HOST: redis
    networks:
      - result-tier
    ports:
      - 5001:4242






volumes:
  db-data:
    driver: local


networks:
  poll-tier:
  result-tier:
  back-tier: